### ISSUE TITLE
Ability to replay a single test

### ISSUE THREAD

**Issue by dawid-nowak** [fido-alliance/conformance-tools-issues#377] opened 2018-08-15 10:04 UTC
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
FIDO2
UAF/U2F/FIDO2 v1.0/v1.1/v1.2

## What is your implementation class?

Server/Client/ASM+Authr

## What is the version of the tool are you using?
FIDO Conformance Tools v0.10.108 (BETA)((BETA) FIDO2 )

## Issue description
It would be nice to have an ability to replay a single test. This would speed up the debugging process.

**Comment by herrjemand** [comment] 2018-08-16 12:43
Hey @dawid-nowak. Yeah, it's been a long requested feature. It's in plans, but it will take me some time. 

Closing due to duplicate of #130

**Closed by herrjemand** 2018-08-16 12:43 UTC
