### ISSUE TITLE
Invalid certificate of Android-safetynet attestation

### ISSUE THREAD

**Issue by sangraecho** [fido-alliance/conformance-tools-issues#342] opened 2018-08-01 06:54 UTC
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?
FIDO2 v1.0

## What is your implementation class?
Server

## What is the version of the tool are you using?
v0.10.935

## What is the OS and the version are you running?
Windows 10

## Issue description
The public key of trust anchor and attestation certificates is null. So the algorithm identifier of the public key could not be read.

![image](https://user-images.githubusercontent.com/5744623/43505848-213621fa-95a3-11e8-9cb4-cab3828c0fed.png)

**Comment by herrjemand** [comment] 2018-08-01 17:10
Can't reproduce your issue @sangraecho Here is what I get:
<img width="819" alt="screenshot 2018-08-01 18 10 34" src="https://user-images.githubusercontent.com/1636116/43537077-382b0886-95b6-11e8-8bc9-f517ede5d039.png">

**Comment by sangraecho** [comment] 2018-08-02 01:07
Public key algorithm should be rsaEncryption instead of sha256WithRSAEncryption.
The below is normal and typical example of X.509 CA Certificate 

![image](https://user-images.githubusercontent.com/5744623/43556626-ae03d12a-963b-11e8-96a3-62c03d0caefe.png)

**Comment by herrjemand** [comment] 2018-08-02 17:43
Resolved in v0.10.106

**Closed by herrjemand** 2018-08-02 17:43 UTC
