### ISSUE TITLE
The tpm, android-key, and android-safetynet attestation tests send "none" attestation.

### ISSUE THREAD

**Issue by prvjhamada** [fido-alliance/conformance-tools-issues#294] opened 2018-07-03 05:26 UTC
## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

v0.10.100

## Issue description

Since the attestation of the argument of getMakeCredentialsChallenge() is none,
For all tests of tpm, android-key, and android-safetynet, parameters with fmt of none will be sent.
I think that attestation should be set to something other than none in order to perform these tests exactly.

**Comment by herrjemand** [comment] 2018-07-08 18:17
@prvjhamada I can't reproduce *(
<img width="419" alt="screenshot 2018-07-08 19 16 57" src="https://user-images.githubusercontent.com/1636116/42422717-81fce564-82e3-11e8-97ae-914711f0c034.png">

**Comment by prvjhamada** [comment] 2018-07-10 06:00
Server Requirements and Transport Binding Profile 7.3.2.1. Example: Credential Creation Options,
According to the example of the request and response, if the attestation of the request is direct, it seems that the attestation of the response is also direct.
In this issue, attestation fmt is none, not android-safetynet because this attestation is none.
In my understanding, attestation sets the value set in the request as it is in the response.
Could you please confirm whether my understanding is correct?

![2018-07-10_15h00_02](https://user-images.githubusercontent.com/38024059/42491937-f4e52e78-8451-11e8-9abb-e191639c2da8.png)

**Comment by herrjemand** [comment] 2018-07-15 16:38
Resolved in v0.10.103

**Closed by herrjemand** 2018-07-15 16:38 UTC
