### ISSUE TITLE
Issues in Android SafetyNet attestation mismatch authority key identifier

### ISSUE THREAD

**Issue by berrikso** [fido-alliance/conformance-tools-issues#465] opened 2019-05-11 09:17 UTC
By submitting this issue you are acknowledging that any information regarding this issue will be publicly available.

If you have privacy concerns, please email [conformance-tools@fidoalliance.org](mailto:conformance-tools@fidoalliance.org)

## What protocol and version of the protocol are you testing?

FIDO2

## What is your implementation class?

Server

## What is the version of the tool are you using?

1.1.2

## What is the OS and the version are you running?

Windows 7

## Issue description

I am experiencing failures when running the test below. 
* ```Server-ServerAuthenticatorAttestationResponse-Resp-B  ``` 
   * ```P-1 Send a valid ServerAuthenticatorAttestationResponse with "android-safetynet" attestation..```

The Android SafetyNet attestation sent by the FCT has the following cert chain
1. Cert[0]
```
Subject	CN = attest.android.com,OU = CWG,O = FIDO Alliance,L = Wakefield,ST = MY,C = US
Issuer	CN = FIDO Alliances FAKE Internet Authority F1,O = FIDO Alliances FAKE Trust Services,C = US
X509v3 Subject Key Identifier: 
                D7:45:13:4F:50:77:2C:68:4A:33:EA:BD:85:BC:A7:D9:2B:95:80:6F
            X509v3 Authority Key Identifier: 
                keyid:A3:DA:17:E0:88:34:DB:C9:A6:5C:00:90:4B:5B:2C:20:14:03:F5:07
```
2. Cert[1]
```
Subject	CN = FIDO Alliances FAKE Internet Authority F1,O = FIDO Alliances FAKE Trust Services,C = US
Issuer	CN = FIDO Alliances FAKE Root CA - S1,O = FIDO Alliance,C = US
 X509v3 Subject Key Identifier: 
                A3:DA:17:E0:88:34:DB:C9:A6:5C:00:90:4B:5B:2C:20:14:03:F5:07
            X509v3 Authority Key Identifier: 
                keyid:AA:36:FF:41:69:D2:9D:8A:3B:D8:1C:65:D3:5B:DE:6B:70:2D:94:90
```

On the FIDO2 server side, I am using metadata from *app-1.1.2\resources\app\modules\fido2-conformance-module\metadata*.

When I observe ```CTAP2RSA15SHA256SafetynetAttestation.metadata```  2 of its 4 root attestion certificates  have CN-s which matches  the issuer of *Cert[1]* above, but **neither** root attestation certificates subject key identifier matches the Authority Key Identifier of Cert[1]. 

These are the 2 root attestation certs that matches the CN-s the issuer of  *Cert[1]*
1.  CN = FIDO Alliances FAKE Root CA - S1,O = FIDO Alliance,C = US
```
X509v3 Subject Key Identifier: 
                C2:14:AA:36:FF:41:69:D2:9D:8A:3B:D8:1C:65:D3:5B:DE:6B:70:2D:94:90
            X509v3 Authority Key Identifier: 
                keyid:AA:36:FF:41:69:D2:9D:8A:3B:D8:1C:65:D3:5B:DE:6B:70:2D:94:90
```
2. CN = FIDO Alliances FAKE Root CA - S1,O = FIDO Alliance,C = US
```
X509v3 Subject Key Identifier: 
                C2:14:AA:36:FF:41:69:D2:9D:8A:3B:D8:1C:65:D3:5B:DE:6B:70:2D:94:90
            X509v3 Authority Key Identifier: 
                .....6.Ai...;..e.[.kp-..
```

Since there is no root attestation subject key identifier that matches the authority key identifier of *Cert[1]*, the certification chain validation fails.

Moreover, do note that both root attestation certificates above have Issuer CNs equal to their Subject CNs, **but** their _Subject Key Identifiers are not equal to their Authority Key Identifiers_. Are those 2 root attestation certificates corrupted ?

Please help to check, and also, let me know in the meantime whether there are Android SafetyNet Attestation Root Certs that matches the *Cert[1]* above

Thank you in advance

**Comment by madwizard-thomas** [comment] 2019-06-10 15:44
I have a similar issue in 1.1.3. I downloaded the metadata zip from the application and in `Virtual RSA PKCS 1.5 SHA256 FIDO2 Conformance Testing CTAP2 Authenticator with SafetyNet attestation.json` the first, second and fourth certificate have invalid Authority Key Identifiers. The third one is correct.
The issue seems similar to #415.
The octet strings in the Authority Key Identifier extension contain `04 16 A0 14 {id bytes}`, which means another octet string containing a constructed context-specific [0] value. However, it should be `30 16 80 14 {id bytes}`, meaning a **sequence** containing a **primitive** context specific [0] value.

**Comment by kishorechandran41** [comment] 2019-07-24 12:18
The above issue is still existing in v1.1.4 also. We are not able to verify the certificate chain due to the same.

**Comment by sbweeden** [comment] 2019-07-31 05:01
Actually in v1.1.4 I think the issue is different. For SafetyNet I am not seeing an issue with the authorityKeyIdentifier, but instead a CRL-related issue: #490

**Comment by herrjemand** [comment] 2019-08-03 18:34
Fixed now

**Closed by herrjemand** 2019-08-03 18:34 UTC
